name: Build Linux

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build gcc pkg-config cmake

      - name: Setup Build Directory
        run: meson setup build -Draylib_path=${{ github.workspace }}/raylib/linux64

      - name: Compile
        run: meson compile -C build

      # Test execution after having an AppImage
      #- name: Test Executable
      #  run: |
      #    LD_LIBRARY_PATH=${{ github.workspace }}/raylib/linux64/lib ./build/zeal-native --help

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zeal-native-linux
          path: build/zeal-native
          retention-days: 30
