name: Build Linux 32-bit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y meson ninja-build gcc-multilib pkg-config cmake
          sudo apt-get install -y libc6-dev-i386

      - name: Build with Meson
        uses: ./.github/actions/meson-build
        with:
          build-dir: build
          cross-file: linux32-cross.build
          raylib-path: ${{ github.workspace }}/raylib/linux32

      # Test execution after having an AppImage
      #- name: Test Executable
      #  run: |
      #    LD_LIBRARY_PATH=${{ github.workspace }}/raylib/linux32/lib ./build/zeal-native --help

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zeal-native-linux32
          path: build/zeal-native
          retention-days: 30
