name: Build Windows 32-bit

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-win32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build gcc-mingw-w64-i686 pkg-config cmake

      - name: Build with Meson
        uses: ./.github/actions/meson-build
        with:
          build-dir: build
          cross-file: win32-cross.build
          raylib-path: ${{ github.workspace }}/raylib/win32

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zeal-native-win32
          path: build/zeal-native.exe
          retention-days: 30
